# Generated by Django 5.2.17 on 2026-10-07 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('limite_prestamos_activos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('contrasena_hash', models.CharField(max_length=256)),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.rol')),
            ],
        ),
    ]
