# Generated by Django 5.2.17 on 2026-10-07 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('autor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.categoria')),
            ],
            options={
                'db_table': 'biblioteca_categoria_libros',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('libro_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(through='biblioteca.CategoriaLibro', to='biblioteca.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='categorialibro',
            name='libro',
            field=models.ForeignKey(db_column='libro_id', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro'),
        ),
        migrations.CreateModel(
            name='LibroAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(db_column='autor_id', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor')),
                ('libro', models.ForeignKey(db_column='libro_id', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
            ],
            options={
                'db_table': 'biblioteca_libros_autores',
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(through='biblioteca.LibroAutor', to='biblioteca.autor'),
        ),
    ]
