# Generated by Django 5.2.17 on 2026-10-07 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_autor_categoria_categorialibro_libro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('ejemplar_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_inventario', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=15)),
                ('libro', models.ForeignKey(db_column='libro_id', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('prestamo_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField()),
                ('ejemplar', models.ForeignKey(db_column='ejemplar_id', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.ejemplar')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('sancion_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_inicio_bloqueo', models.DateField(blank=True, null=True)),
                ('fecha_fin_bloqueo', models.DateField(blank=True, null=True)),
                ('prestamo', models.ForeignKey(db_column='prestamo_id', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.prestamo')),
            ],
        ),
    ]
